/*
 * Copyright 2014 STNet,Inc..
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mycompany.apps.domain.dto;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 *
 * @author stnetadmin
 */
public class Users implements UserDetails {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.id
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.username
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.password
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.mail_address
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.enabled
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.account_non_locked
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Boolean accountNonLocked;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.account_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Boolean accountNonExpired;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.account_expiration_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Date accountExpirationDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.credentials_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Boolean credentialsNonExpired;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.login_failed_count
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Short loginFailedCount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.last_login_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.rec_insert_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Date recInsertDatetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.rec_insert_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private String recInsertUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.rec_update_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private Date recUpdateDatetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column public.users.rec_update_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    private String recUpdateUser;

    /**
     *
     */
    private GrantedAuthority authorities;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.username
     *
     * @return the value of public.users.username
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.username
     *
     * @param username the value for public.users.username
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.mail_address
     *
     * @return the value of public.users.mail_address
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.mail_address
     *
     * @param mailAddress the value for public.users.mail_address
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.enabled
     *
     * @return the value of public.users.enabled
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.enabled
     *
     * @param enabled the value for public.users.enabled
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.account_non_locked
     *
     * @return the value of public.users.account_non_locked
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Boolean getAccountNonLocked() {
        return accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.account_non_locked
     *
     * @param accountNonLocked the value for public.users.account_non_locked
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setAccountNonLocked(Boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.account_non_expired
     *
     * @return the value of public.users.account_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Boolean getAccountNonExpired() {
        return accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.account_non_expired
     *
     * @param accountNonExpired the value for public.users.account_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setAccountNonExpired(Boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.account_expiration_date
     *
     * @return the value of public.users.account_expiration_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Date getAccountExpirationDate() {
        return accountExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.account_expiration_date
     *
     * @param accountExpirationDate the value for
     * public.users.account_expiration_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setAccountExpirationDate(Date accountExpirationDate) {
        this.accountExpirationDate = accountExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.credentials_non_expired
     *
     * @return the value of public.users.credentials_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Boolean getCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.credentials_non_expired
     *
     * @param credentialsNonExpired the value for
     * public.users.credentials_non_expired
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setCredentialsNonExpired(Boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.login_failed_count
     *
     * @return the value of public.users.login_failed_count
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Short getLoginFailedCount() {
        return loginFailedCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.login_failed_count
     *
     * @param loginFailedCount the value for public.users.login_failed_count
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setLoginFailedCount(Short loginFailedCount) {
        this.loginFailedCount = loginFailedCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.last_login_date
     *
     * @return the value of public.users.last_login_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.last_login_date
     *
     * @param lastLoginDate the value for public.users.last_login_date
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.rec_insert_datetime
     *
     * @return the value of public.users.rec_insert_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Date getRecInsertDatetime() {
        return recInsertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.rec_insert_datetime
     *
     * @param recInsertDatetime the value for public.users.rec_insert_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setRecInsertDatetime(Date recInsertDatetime) {
        this.recInsertDatetime = recInsertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.rec_insert_user
     *
     * @return the value of public.users.rec_insert_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public String getRecInsertUser() {
        return recInsertUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.rec_insert_user
     *
     * @param recInsertUser the value for public.users.rec_insert_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setRecInsertUser(String recInsertUser) {
        this.recInsertUser = recInsertUser == null ? null : recInsertUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.rec_update_datetime
     *
     * @return the value of public.users.rec_update_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public Date getRecUpdateDatetime() {
        return recUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.rec_update_datetime
     *
     * @param recUpdateDatetime the value for public.users.rec_update_datetime
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setRecUpdateDatetime(Date recUpdateDatetime) {
        this.recUpdateDatetime = recUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column public.users.rec_update_user
     *
     * @return the value of public.users.rec_update_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public String getRecUpdateUser() {
        return recUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column public.users.rec_update_user
     *
     * @param recUpdateUser the value for public.users.rec_update_user
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    public void setRecUpdateUser(String recUpdateUser) {
        this.recUpdateUser = recUpdateUser == null ? null : recUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Users other = (Users) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getMailAddress() == null ? other.getMailAddress() == null : this.getMailAddress().equals(other.getMailAddress()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getAccountNonLocked() == null ? other.getAccountNonLocked() == null : this.getAccountNonLocked().equals(other.getAccountNonLocked()))
            && (this.getAccountNonExpired() == null ? other.getAccountNonExpired() == null : this.getAccountNonExpired().equals(other.getAccountNonExpired()))
            && (this.getAccountExpirationDate() == null ? other.getAccountExpirationDate() == null : this.getAccountExpirationDate().equals(other.getAccountExpirationDate()))
            && (this.getCredentialsNonExpired() == null ? other.getCredentialsNonExpired() == null : this.getCredentialsNonExpired().equals(other.getCredentialsNonExpired()))
            && (this.getLoginFailedCount() == null ? other.getLoginFailedCount() == null : this.getLoginFailedCount().equals(other.getLoginFailedCount()))
            && (this.getLastLoginDate() == null ? other.getLastLoginDate() == null : this.getLastLoginDate().equals(other.getLastLoginDate()))
            && (this.getRecInsertDatetime() == null ? other.getRecInsertDatetime() == null : this.getRecInsertDatetime().equals(other.getRecInsertDatetime()))
            && (this.getRecInsertUser() == null ? other.getRecInsertUser() == null : this.getRecInsertUser().equals(other.getRecInsertUser()))
            && (this.getRecUpdateDatetime() == null ? other.getRecUpdateDatetime() == null : this.getRecUpdateDatetime().equals(other.getRecUpdateDatetime()))
            && (this.getRecUpdateUser() == null ? other.getRecUpdateUser() == null : this.getRecUpdateUser().equals(other.getRecUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getMailAddress() == null) ? 0 : getMailAddress().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getAccountNonLocked() == null) ? 0 : getAccountNonLocked().hashCode());
        result = prime * result + ((getAccountNonExpired() == null) ? 0 : getAccountNonExpired().hashCode());
        result = prime * result + ((getAccountExpirationDate() == null) ? 0 : getAccountExpirationDate().hashCode());
        result = prime * result + ((getCredentialsNonExpired() == null) ? 0 : getCredentialsNonExpired().hashCode());
        result = prime * result + ((getLoginFailedCount() == null) ? 0 : getLoginFailedCount().hashCode());
        result = prime * result + ((getLastLoginDate() == null) ? 0 : getLastLoginDate().hashCode());
        result = prime * result + ((getRecInsertDatetime() == null) ? 0 : getRecInsertDatetime().hashCode());
        result = prime * result + ((getRecInsertUser() == null) ? 0 : getRecInsertUser().hashCode());
        result = prime * result + ((getRecUpdateDatetime() == null) ? 0 : getRecUpdateDatetime().hashCode());
        result = prime * result + ((getRecUpdateUser() == null) ? 0 : getRecUpdateUser().hashCode());
        return result;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return (Collection<? extends GrantedAuthority>) authorities;
    }

    public void setAuthorities(List<String> roles) {
        List<GrantedAuthority> listOfAuthorities = new ArrayList<GrantedAuthority>();
        for (String role : roles) {
            listOfAuthorities.add(new Roles(role));
        }
    }

    @Override
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }

    @Override
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

}
