package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.Permissions;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    Permissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int updateByPrimaryKey(Permissions record);
}