package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PermissionsIdSeq;

public interface PermissionsIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(PermissionsIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(PermissionsIdSeq record);
}