package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkPermissions;

public interface PkPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(PkPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(PkPermissions record);
}