package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkRoles;

public interface PkRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(PkRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(PkRoles record);
}