package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkRolesUsers;

public interface PkRolesUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int insert(PkRolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int insertSelective(PkRolesUsers record);
}