package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkUsers;

public interface PkUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_users
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(PkUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_users
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(PkUsers record);
}