package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.RolesUsers;
import org.apache.ibatis.annotations.Param;

public interface RolesUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int deleteByPrimaryKey(@Param("roleId") Short roleId, @Param("userId") Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int insert(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int insertSelective(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    RolesUsers selectByPrimaryKey(@Param("roleId") Short roleId, @Param("userId") Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int updateByPrimaryKeySelective(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    int updateByPrimaryKey(RolesUsers record);
}