package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.RolePermissions;

public interface RolePermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_permissions
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(RolePermissions record);
}