package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.RolesIdSeq;

public interface RolesIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(RolesIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(RolesIdSeq record);
}