package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.RoleMembers;

public interface RoleMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_members
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(RoleMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_members
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(RoleMembers record);
}