package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.Roles;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    Roles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int updateByPrimaryKey(Roles record);
}