package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.UsersUsernameKey;

public interface UsersUsernameKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(UsersUsernameKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(UsersUsernameKey record);
}