package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.UsersIdSeq;

public interface UsersIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insert(UsersIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_id_seq
     *
     * @mbggenerated Tue Jun 17 15:11:32 JST 2014
     */
    int insertSelective(UsersIdSeq record);
}