package com.mycompany.apps.domain.entities;

public class PkRolesUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pk_roles_users.role_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    private Short roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pk_roles_users.user_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    private Short userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pk_roles_users.role_id
     *
     * @return the value of public.pk_roles_users.role_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pk_roles_users.role_id
     *
     * @param roleId the value for public.pk_roles_users.role_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pk_roles_users.user_id
     *
     * @return the value of public.pk_roles_users.user_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    public Short getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pk_roles_users.user_id
     *
     * @param userId the value for public.pk_roles_users.user_id
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    public void setUserId(Short userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PkRolesUsers other = (PkRolesUsers) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles_users
     *
     * @mbggenerated Wed Jun 18 23:12:48 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }
}