package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.Permissions;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    Permissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKey(Permissions record);
}