package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.PermissionsIdSeq;

public interface PermissionsIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(PermissionsIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.permissions_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(PermissionsIdSeq record);
}