package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.PkPermissions;

public interface PkPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(PkPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(PkPermissions record);
}