package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.PkRoles;

public interface PkRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(PkRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(PkRoles record);
}