package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.PkUsers;

public interface PkUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(PkUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(PkUsers record);
}