package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.Roles;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    Roles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKey(Roles record);
}