package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.RolesIdSeq;

public interface RolesIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(RolesIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(RolesIdSeq record);
}