package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.RoleMembers;

public interface RoleMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_members
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(RoleMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_members
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(RoleMembers record);
}