package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.RolePermissions;

public interface RolePermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_permissions
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(RolePermissions record);
}