package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.UsersIdSeq;

public interface UsersIdSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(UsersIdSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_id_seq
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(UsersIdSeq record);
}