package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.Users;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    Users selectByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int updateByPrimaryKey(Users record);
}