package com.mycompany.apps.mappers;

import com.mycompany.apps.entities.UsersUsernameKey;

public interface UsersUsernameKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insert(UsersUsernameKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    int insertSelective(UsersUsernameKey record);
}