package com.mycompany.apps.entities;

public class UsersUsernameKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users_username_key.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users_username_key.username
     *
     * @return the value of public.users_username_key.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users_username_key.username
     *
     * @param username the value for public.users_username_key.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UsersUsernameKey other = (UsersUsernameKey) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users_username_key
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        return result;
    }
}