package com.mycompany.apps.entities;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.mail_address
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.enabled
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.account_locked
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Boolean accountLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.login_failed_count
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Short loginFailedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.last_login_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.account_expiration_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Date accountExpirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.rec_insert_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Date recInsertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.rec_insert_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String recInsertUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.rec_update_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private Date recUpdateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.rec_update_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    private String recUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.username
     *
     * @return the value of public.users.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.username
     *
     * @param username the value for public.users.username
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.mail_address
     *
     * @return the value of public.users.mail_address
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.mail_address
     *
     * @param mailAddress the value for public.users.mail_address
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.enabled
     *
     * @return the value of public.users.enabled
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.enabled
     *
     * @param enabled the value for public.users.enabled
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.account_locked
     *
     * @return the value of public.users.account_locked
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Boolean getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.account_locked
     *
     * @param accountLocked the value for public.users.account_locked
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setAccountLocked(Boolean accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.login_failed_count
     *
     * @return the value of public.users.login_failed_count
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Short getLoginFailedCount() {
        return loginFailedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.login_failed_count
     *
     * @param loginFailedCount the value for public.users.login_failed_count
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setLoginFailedCount(Short loginFailedCount) {
        this.loginFailedCount = loginFailedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.last_login_date
     *
     * @return the value of public.users.last_login_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.last_login_date
     *
     * @param lastLoginDate the value for public.users.last_login_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.account_expiration_date
     *
     * @return the value of public.users.account_expiration_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Date getAccountExpirationDate() {
        return accountExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.account_expiration_date
     *
     * @param accountExpirationDate the value for public.users.account_expiration_date
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setAccountExpirationDate(Date accountExpirationDate) {
        this.accountExpirationDate = accountExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.rec_insert_datetime
     *
     * @return the value of public.users.rec_insert_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Date getRecInsertDatetime() {
        return recInsertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.rec_insert_datetime
     *
     * @param recInsertDatetime the value for public.users.rec_insert_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setRecInsertDatetime(Date recInsertDatetime) {
        this.recInsertDatetime = recInsertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.rec_insert_user
     *
     * @return the value of public.users.rec_insert_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getRecInsertUser() {
        return recInsertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.rec_insert_user
     *
     * @param recInsertUser the value for public.users.rec_insert_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setRecInsertUser(String recInsertUser) {
        this.recInsertUser = recInsertUser == null ? null : recInsertUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.rec_update_datetime
     *
     * @return the value of public.users.rec_update_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public Date getRecUpdateDatetime() {
        return recUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.rec_update_datetime
     *
     * @param recUpdateDatetime the value for public.users.rec_update_datetime
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setRecUpdateDatetime(Date recUpdateDatetime) {
        this.recUpdateDatetime = recUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.rec_update_user
     *
     * @return the value of public.users.rec_update_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public String getRecUpdateUser() {
        return recUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.rec_update_user
     *
     * @param recUpdateUser the value for public.users.rec_update_user
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    public void setRecUpdateUser(String recUpdateUser) {
        this.recUpdateUser = recUpdateUser == null ? null : recUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Users other = (Users) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getMailAddress() == null ? other.getMailAddress() == null : this.getMailAddress().equals(other.getMailAddress()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getAccountLocked() == null ? other.getAccountLocked() == null : this.getAccountLocked().equals(other.getAccountLocked()))
            && (this.getLoginFailedCount() == null ? other.getLoginFailedCount() == null : this.getLoginFailedCount().equals(other.getLoginFailedCount()))
            && (this.getLastLoginDate() == null ? other.getLastLoginDate() == null : this.getLastLoginDate().equals(other.getLastLoginDate()))
            && (this.getAccountExpirationDate() == null ? other.getAccountExpirationDate() == null : this.getAccountExpirationDate().equals(other.getAccountExpirationDate()))
            && (this.getRecInsertDatetime() == null ? other.getRecInsertDatetime() == null : this.getRecInsertDatetime().equals(other.getRecInsertDatetime()))
            && (this.getRecInsertUser() == null ? other.getRecInsertUser() == null : this.getRecInsertUser().equals(other.getRecInsertUser()))
            && (this.getRecUpdateDatetime() == null ? other.getRecUpdateDatetime() == null : this.getRecUpdateDatetime().equals(other.getRecUpdateDatetime()))
            && (this.getRecUpdateUser() == null ? other.getRecUpdateUser() == null : this.getRecUpdateUser().equals(other.getRecUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbggenerated Sun Jun 15 20:25:56 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getMailAddress() == null) ? 0 : getMailAddress().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getAccountLocked() == null) ? 0 : getAccountLocked().hashCode());
        result = prime * result + ((getLoginFailedCount() == null) ? 0 : getLoginFailedCount().hashCode());
        result = prime * result + ((getLastLoginDate() == null) ? 0 : getLastLoginDate().hashCode());
        result = prime * result + ((getAccountExpirationDate() == null) ? 0 : getAccountExpirationDate().hashCode());
        result = prime * result + ((getRecInsertDatetime() == null) ? 0 : getRecInsertDatetime().hashCode());
        result = prime * result + ((getRecInsertUser() == null) ? 0 : getRecInsertUser().hashCode());
        result = prime * result + ((getRecUpdateDatetime() == null) ? 0 : getRecUpdateDatetime().hashCode());
        result = prime * result + ((getRecUpdateUser() == null) ? 0 : getRecUpdateUser().hashCode());
        return result;
    }
}